name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  backend:
    name: Django Backend Test & Deploy
    runs-on: ubuntu-latest
          
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'
          

      - name: Install dependencies
        run: |
          pip install -r Backend/requirements.txt

      - name: Run Django Migrations
        run: |
          python Backend/quiz/manage.py migrate

      - name: Run Tests
        run: |
          python Backend/quiz/manage.py test

      - name: Build & Push Docker Image
        run: |
          docker build -t shubhs242/quiz-backend ./Backend
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push shubhs242/quiz-backend

  frontend:
    name: React Frontend Build & Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '23.9'

      - name: Install dependencies
        run: |
          cd frontend
          npm install

      - name: Build Frontend
        run: |
          cd frontend
          npm run build

      - name: Build & Push Docker Image
        run: |
          docker build -t shubhs242/quiz-frontend ./frontend
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push shubhs242/quiz-frontend
